In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
!yes | unzip /content/gdrive/MyDrive/151B_data/new_train.zip > /dev/null
!yes | unzip /content/gdrive/MyDrive/151B_data/new_val_in.zip > /dev/null

In [6]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import os, os.path 
import numpy 
import pickle
from glob import glob


"""Change to the data folder"""
new_path = "data/new_train"

# number of sequences in each dataset
# train:205942  val:3200 test: 36272 
# sequences sampled at 10HZ rate

In [7]:
class ArgoverseDataset(Dataset):
    """Dataset class for Argoverse"""
    def __init__(self, data_path: str, transform=None):
        super(ArgoverseDataset, self).__init__()
        self.data_path = data_path
        self.transform = transform

        self.pkl_list = glob(os.path.join(self.data_path, '*'))
        self.pkl_list.sort()
        
    def __len__(self):
        return len(self.pkl_list)

    def __getitem__(self, idx):

        pkl_path = self.pkl_list[idx]
        with open(pkl_path, 'rb') as f:
            data = pickle.load(f)
            
        if self.transform:
            data = self.transform(data)

        return data


# intialize a dataset
val_dataset  = ArgoverseDataset(data_path=new_path)

In [8]:
batch_sz = 100

def my_collate(batch):
    """ collate lists of samples into batches, create [ batch_sz x agent_sz x seq_len x feature] """

    inp = [[scene['p_in'], scene['v_in']] for scene in batch]
    out = [[scene['p_out'], scene['v_out']] for scene in batch]
    mask = [scene['car_mask'] for scene in batch]

    inp = torch.LongTensor(inp)
    out = torch.LongTensor(out)
    mask = torch.LongTensor(mask)
    return [inp, out, mask]

val_loader = DataLoader(val_dataset,batch_size=batch_sz, shuffle = False, collate_fn=my_collate, num_workers=0)

In [ ]:
'''
max_p_x = 0
min_p_x = 5000
max_p_y = 0
min_p_y = 5000
max_v_x = 0
min_v_x = 100
max_v_y = 0
min_v_y = 100

for i_batch, sample_batch in enumerate(val_loader):
    inp, out, mask = sample_batch
    for i in inp:
      if i[0][:,0].max()> max_p_x:
        max_p_x = i[0][:,0].max()
      if i[0][:,0].min() < min_p_x:
        min_p_x = i[0][:,0].min()
      if i[0][:,1].max()> max_p_y:
        max_p_y = i[0][:,1].max()
      if i[0][:,1].min() < min_p_y:
        min_p_y = i[0][:,1].min()

      if i[1][:,0].max()> max_v_x:
        max_v_x = i[1][:,0].max()
      if i[1][:,0].min()< min_v_x:
        min_v_x = i[1][:,0].min()
      if i[1][:,1].max()> max_v_y:
        max_v_y = i[1][:,1].max()
      if i[1][:,1].min()< min_v_y:
        min_v_y = i[1][:,1].min()

    for o in out:
      if o[0][:,0].max()> max_p_x:
        max_p_x = o[0][:,0].max()
      if o[0][:,0].min() < min_p_x:
        min_p_x = o[0][:,0].min()
      if o[0][:,1].max()> max_p_y:
        max_p_y = o[0][:,1].max()
      if o[0][:,1].min() < min_p_y:
        min_p_y = o[0][:,1].min()

      if o[1][:,0].max()> max_v_x:
        max_v_x = o[1][:,0].max()
      if o[1][:,0].min()< min_v_x:
        min_v_x = o[1][:,0].min()
      if o[1][:,1].max()> max_v_y:
        max_v_y = o[1][:,1].max()
      if o[1][:,1].min()< min_v_y:
        min_v_y = o[1][:,1].min()

    if(i_batch%100==0):
      print(i_batch)

print(max_p_x, min_p_x, max_p_y, min_p_y) # [4800,-50,4800,-50]
print(max_v_x, min_v_x, max_v_y, min_v_y) # [200,-200,200,-200]
'''

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class Trajectory(nn.Module):

    def __init__(self):
        super(Trajectory, self).__init__()

        self.p_in = nn.Linear(2,32) # N, 19, 2
        self.v_in = nn.Linear(2,32) # N, 19, 2
        
        self.encoder = nn.LSTM(64, 64, 1) # input 19, N, 4 output 19, N, 64

        self.decoder_p = nn.LSTM(64, 128,1) # input 30, N, 64 output 30, N, 128
        self.decoder_v = nn.LSTM(64, 128,1) # input 30, N, 64 output 30, N, 128

        self.p_out = nn.Linear(128,2)
        self.v_out = nn.Linear(128,2)

    def forward(self, p, v, holder):
        batch = p.shape[0]
        x_p = self.p_in(p)
        x_v = self.v_in(v)

        x = torch.cat((x_p,x_v),dim=2)
        x = x.view(19,batch,64)
        x,_ = self.encoder(x)

        x = torch.cat((x,holder),dim=0)

        x_p,_ = self.decoder_p(x)
        x_v,_ = self.decoder_v(x)

        x_p = x_p.view(batch,30,128)
        x_v = x_v.view(batch,30,128)
        x_p = self.p_out(x_p)
        x_v = self.v_out(x_v)

        return x_p, x_v

In [ ]:
'''
import numpy as np
model = Trajectory().double()
print(model)

p = np.zeros((4,19,2))
v = np.zeros((4,19,2))
p_torch = torch.tensor(p)
v_torch = torch.tensor(v)

output = model(p_torch, v_torch)
print(len(output))
print(output[0].shape)
'''

In [11]:
from tqdm import tqdm

In [16]:
model = Trajectory().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
epoch = 2

for i in range(epoch):
  model.train()
  epoch_loss = 0
  for i_batch, sample_batch in tqdm(enumerate(val_loader), total=len(val_loader), leave=False):
    inp, out, mask = sample_batch
    batch = inp.shape[0]

    holder = torch.zeros((11,batch*60,64)).to(device)

    p_in = (inp[:,0].reshape(batch*60,19,2).to(device)-2400.)/2400.
    v_in = inp[:,1].reshape(batch*60,19,2).to(device)/200.
    p_out = (out[:,0].reshape(batch*60,30,2).to(device)-2400.)/2400.
    v_out = out[:,1].reshape(batch*60,30,2).to(device)/200.

    pred = model(p_in, v_in, holder)


    loss = 0
    p_criteria = nn.MSELoss()
    p_loss = torch.sqrt(p_criteria(pred[0], p_out))

    v_criteria = nn.MSELoss()
    v_loss = torch.sqrt(v_criteria(pred[1], v_out))

    if (i_batch%200==0 and i_batch!=0):
      print(pred[0][0]*2400.+2400., p_out[0]*2400.+2400.)
      print(pred[1][0]*200., v_out[0]*200.)
      print(i_batch, p_loss, v_loss)
    loss = p_loss + v_loss
    epoch_loss += loss

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(i, epoch_loss)


  0%|          | 0/2060 [00:00<?, ?it/s]<ipython-input-8-db1da268cb2b>:10: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  inp = torch.LongTensor(inp)
<ipython-input-8-db1da268cb2b>:11: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  out = torch.LongTensor(out)
<ipython-input-8-db1da268cb2b>:12: DeprecationWarning: an integer is required (got type numpy.float32).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  mask = torch.LongTensor(mask)
 10%|▉         | 201/2060 [03:19<31:15,  1.01s/it]

tensor([[2184.3801, 2322.3022],
        [2184.3555, 2322.3254],
        [2184.4783, 2322.4482],
        [2184.4783, 2322.4482],
        [2184.4927, 2322.4944],
        [2184.4927, 2322.4944],
        [2184.4985, 2322.4990],
        [2184.4985, 2322.4990],
        [2184.5371, 2322.5342],
        [2184.5371, 2322.5342],
        [2184.5486, 2322.4871],
        [2184.5752, 2322.5266],
        [2184.4321, 2322.4001],
        [2184.4705, 2322.4419],
        [2184.5552, 2322.4246],
        [2184.5552, 2322.4246],
        [2184.4707, 2322.3838],
        [2184.4707, 2322.3838],
        [2184.4502, 2322.3635],
        [2183.1079, 2321.0581],
        [2183.1079, 2321.0581],
        [2182.9958, 2320.9780],
        [2183.1079, 2321.0581],
        [2183.1079, 2321.0581],
        [2183.1079, 2321.0581],
        [2183.1079, 2321.0581],
        [2182.9958, 2320.9780],
        [2183.1079, 2321.0581],
        [2183.2141, 2321.1523],
        [2182.9910, 2320.9143]], device='cuda:0', grad_fn=<AddBackward0>

 19%|█▉        | 401/2060 [06:43<27:59,  1.01s/it]

tensor([[1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.5914, 1795.6309],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873],
        [1665.9496, 1795.9873]], device='cuda:0', grad_fn=<AddBackward0>

 29%|██▉       | 601/2060 [10:09<25:09,  1.03s/it]

tensor([[1479.5822, 1627.4949],
        [1480.9709, 1628.9172],
        [1480.6931, 1628.6401],
        [1480.6931, 1628.6401],
        [1480.0980, 1628.1377],
        [1479.9932, 1627.9919],
        [1479.5981, 1627.5605],
        [1479.3529, 1627.3418],
        [1479.3529, 1627.3418],
        [1479.2704, 1627.1931],
        [1478.5237, 1626.5450],
        [1478.3546, 1626.3682],
        [1477.6996, 1625.6030],
        [1477.6996, 1625.6030],
        [1477.1011, 1625.0623],
        [1477.2515, 1625.1899],
        [1476.7942, 1624.7319],
        [1476.4751, 1624.4888],
        [1476.3743, 1624.3435],
        [1478.6748, 1626.6333],
        [1477.9631, 1626.0105],
        [1477.5234, 1625.4934],
        [1476.9482, 1624.9624],
        [1476.4846, 1624.4851],
        [1476.3528, 1624.2659],
        [1472.2949, 1620.2053],
        [1477.2810, 1625.2150],
        [1473.1367, 1621.1553],
        [1477.0559, 1625.0162],
        [1474.0439, 1622.0110]], device='cuda:0', grad_fn=<AddBackward0>

 39%|███▉      | 801/2060 [13:48<23:12,  1.11s/it]

tensor([[1210.2167, 1347.6173],
        [1210.9618, 1347.9664],
        [1211.2721, 1348.4576],
        [1211.7981, 1348.8787],
        [1211.1692, 1348.3632],
        [1211.3270, 1348.5569],
        [1211.3270, 1348.5569],
        [1211.6646, 1348.8748],
        [1211.7748, 1348.9745],
        [1212.1804, 1349.4939],
        [1210.9948, 1348.2463],
        [1212.0193, 1349.3408],
        [1211.5973, 1348.8911],
        [1212.3143, 1349.6881],
        [1212.0115, 1349.3088],
        [1211.7517, 1349.1417],
        [1211.4678, 1348.8071],
        [1211.1277, 1348.4376],
        [1210.7087, 1348.0377],
        [1204.2034, 1341.1644],
        [1207.3580, 1344.3564],
        [1204.5994, 1341.5729],
        [1205.1331, 1342.0607],
        [1205.6104, 1342.5941],
        [1207.7727, 1344.7920],
        [1206.9819, 1343.9731],
        [1203.9792, 1340.8840],
        [1208.0939, 1345.1194],
        [1203.9940, 1340.9777],
        [1206.6699, 1343.6014]], device='cuda:0', grad_fn=<AddBackward0>

 49%|████▊     | 1001/2060 [17:27<19:16,  1.09s/it]

tensor([[574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.2430, 717.3064],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885],
        [574.6249, 717.6885]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 187., 1547.],
        [ 187., 1547.],
        [ 

 58%|█████▊    | 1201/2060 [21:00<14:20,  1.00s/it]

tensor([[850.6887, 989.8662],
        [851.1780, 990.1497],
        [851.1780, 990.1497],
        [851.3761, 990.5201],
        [852.4347, 991.5372],
        [851.9873, 991.0973],
        [852.2729, 991.3545],
        [852.6292, 991.7281],
        [852.8534, 992.0024],
        [853.2140, 992.3175],
        [853.2140, 992.3175],
        [854.0627, 993.2147],
        [854.0621, 993.1274],
        [854.8687, 994.0327],
        [854.4663, 993.5967],
        [855.4070, 994.4913],
        [854.4242, 993.5388],
        [854.5922, 993.7070],
        [854.9321, 994.1168],
        [844.1997, 983.3190],
        [843.6670, 982.8529],
        [844.6565, 983.7999],
        [845.5177, 984.6639],
        [845.7810, 984.9009],
        [845.5344, 984.6882],
        [845.6639, 984.7959],
        [845.9167, 985.0004],
        [846.3326, 985.5535],
        [846.3444, 985.5746],
        [846.8086, 985.9208]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2808., 1281.],
        [2808., 1282.],
        [2

 68%|██████▊   | 1401/2060 [24:22<10:59,  1.00s/it]

tensor([[735.5645, 885.5170],
        [735.2107, 885.1093],
        [735.4055, 885.3547],
        [735.5403, 885.4563],
        [736.0164, 886.0814],
        [735.8331, 885.7936],
        [736.1539, 886.0634],
        [736.2493, 886.1509],
        [736.9910, 887.0115],
        [736.8850, 886.7921],
        [737.2556, 887.2469],
        [737.2234, 887.2050],
        [737.9905, 887.8927],
        [738.5142, 888.5444],
        [737.8077, 887.7064],
        [738.0046, 887.9310],
        [739.4199, 889.3624],
        [738.2266, 888.0409],
        [738.2527, 888.1311],
        [727.4155, 877.4525],
        [728.0657, 878.0614],
        [722.3954, 872.0701],
        [732.7550, 883.2041],
        [730.8988, 880.7980],
        [728.0723, 878.2611],
        [729.2618, 879.3374],
        [728.9734, 878.9944],
        [729.1772, 879.2424],
        [728.3644, 878.3995],
        [730.5756, 880.4224]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 541.0000, 3074.0000],
        [ 541.0000, 3075.0

 78%|███████▊  | 1601/2060 [27:42<07:48,  1.02s/it]

tensor([[766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [766.5659, 896.2690],
        [771.5557, 901.1201],
        [772.0718, 901.7197],
        [771.5557, 901.1201],
        [771.5557, 901.1201],
        [771.5557, 901.1201],
        [771.5557, 901.1201],
        [770.4374, 900.1072],
        [772.0718, 901.7197],
        [771.5557, 901.1201],
        [771.5557, 901.1201],
        [771.5557, 901.1201]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2771., 1393.],
        [2771., 1393.],
        [2

 87%|████████▋ | 1801/2060 [31:05<04:21,  1.01s/it]

tensor([[523.6989, 668.2236],
        [525.0516, 669.6166],
        [523.4006, 667.9452],
        [523.7197, 668.2666],
        [522.9619, 667.5692],
        [523.2041, 667.8956],
        [523.0306, 667.7023],
        [522.5166, 667.0988],
        [522.8206, 667.4237],
        [523.0586, 667.8092],
        [522.0809, 666.6456],
        [522.3890, 666.9016],
        [522.1316, 666.6859],
        [520.6106, 665.1340],
        [521.7672, 666.3297],
        [521.6831, 666.2716],
        [520.9591, 665.5570],
        [521.7002, 666.4021],
        [520.6648, 665.1958],
        [537.1060, 681.7332],
        [542.1010, 686.5604],
        [535.0581, 679.9274],
        [534.2646, 679.2490],
        [534.7870, 679.6682],
        [532.6743, 677.7480],
        [535.5037, 680.3359],
        [535.1263, 679.9471],
        [548.4081, 692.2338],
        [534.4258, 679.5408],
        [534.0531, 679.0900]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 740.9999, 2181.0000],
        [ 740.9999, 2180.0

 97%|█████████▋| 2001/2060 [34:32<01:01,  1.04s/it]

tensor([[463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.1238, 620.6877],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656],
        [463.6753, 621.1656]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 790., 1984.],
        [ 790., 1984.],
        [ 

  0%|          | 0/2060 [00:00<?, ?it/s]           

0 tensor(742.5723, device='cuda:0', grad_fn=<AddBackward0>)


 10%|▉         | 201/2060 [03:25<34:11,  1.10s/it]

tensor([[839.9425, 958.3593],
        [840.6033, 959.1627],
        [840.9102, 959.5602],
        [840.9102, 959.5602],
        [841.0638, 959.7299],
        [841.0638, 959.7299],
        [841.3370, 959.9838],
        [841.3370, 959.9838],
        [841.3307, 959.9331],
        [841.3307, 959.9331],
        [840.6215, 959.1980],
        [840.8895, 959.5007],
        [840.3279, 958.9299],
        [840.3718, 958.9542],
        [840.0320, 958.4779],
        [840.0320, 958.4779],
        [839.5693, 958.1870],
        [839.5693, 958.1870],
        [839.5869, 958.1893],
        [834.8760, 953.4575],
        [834.8760, 953.4575],
        [834.1652, 952.8265],
        [834.8760, 953.4575],
        [834.8760, 953.4575],
        [834.8760, 953.4575],
        [834.8760, 953.4575],
        [834.1652, 952.8265],
        [834.8760, 953.4575],
        [835.3220, 953.9403],
        [833.4967, 952.0885]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[3319., 1995.],
        [3319., 1995.],
        [3

 19%|█▉        | 401/2060 [07:00<31:18,  1.13s/it]

tensor([[455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.1921, 578.5958],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517],
        [455.2659, 578.7517]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2191.,  727.],
        [2191.,  727.],
        [2

 29%|██▉       | 601/2060 [10:31<24:38,  1.01s/it]

tensor([[598.5342, 744.7146],
        [600.5592, 746.7601],
        [600.2943, 746.5375],
        [600.2943, 746.5375],
        [599.7014, 745.8966],
        [599.4646, 745.7163],
        [598.8800, 745.2036],
        [598.4758, 744.7393],
        [598.4758, 744.7393],
        [598.4250, 744.6433],
        [597.9103, 744.2167],
        [597.8019, 744.0527],
        [597.0779, 743.2473],
        [597.0779, 743.2473],
        [596.1799, 742.4424],
        [596.3612, 742.6337],
        [595.8041, 742.0841],
        [595.6605, 741.9418],
        [595.5515, 741.8458],
        [598.5488, 744.7405],
        [597.9539, 744.1963],
        [597.1532, 743.3081],
        [596.5475, 742.8342],
        [595.9447, 742.1442],
        [595.7328, 741.9385],
        [590.1636, 736.4237],
        [597.3657, 743.6145],
        [591.9497, 738.3684],
        [597.1222, 743.2974],
        [593.2909, 739.5780]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2979., 1447.],
        [2979., 1447.],
        [2

 39%|███▉      | 801/2060 [13:59<21:17,  1.01s/it]

tensor([[594.6921, 708.1498],
        [594.2122, 707.5483],
        [594.8054, 708.0454],
        [594.9244, 708.3058],
        [594.6538, 708.0203],
        [594.6680, 708.0289],
        [594.6680, 708.0289],
        [595.0486, 708.4893],
        [595.1837, 708.7041],
        [595.7153, 709.3574],
        [594.3452, 707.8528],
        [595.6008, 709.3132],
        [594.9423, 708.5885],
        [595.6829, 709.3942],
        [595.3938, 708.9176],
        [595.4673, 709.1603],
        [594.7756, 708.4102],
        [594.6489, 708.3010],
        [593.9545, 707.6395],
        [588.6932, 701.9066],
        [591.9226, 705.1390],
        [588.9856, 702.1113],
        [589.3907, 702.4940],
        [589.9049, 703.1086],
        [592.2811, 705.5096],
        [591.3606, 704.5138],
        [588.0992, 701.2979],
        [592.5310, 705.7501],
        [588.2515, 701.4501],
        [590.7173, 703.8683]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2964., 1436.],
        [2963., 1437.],
        [2

 49%|████▊     | 1001/2060 [17:29<20:00,  1.13s/it]

tensor([[306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.6689, 441.1946],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927],
        [306.7263, 441.2927]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 187., 1547.],
        [ 187., 1547.],
        [ 

 58%|█████▊    | 1201/2060 [21:12<15:53,  1.11s/it]

tensor([[519.2072, 649.9360],
        [519.2773, 650.0779],
        [519.2773, 650.0779],
        [519.4187, 650.2927],
        [520.4564, 651.3289],
        [519.9714, 650.7289],
        [519.9988, 650.7845],
        [520.2961, 651.1256],
        [520.3577, 651.3027],
        [520.7441, 651.5759],
        [520.7441, 651.5759],
        [521.4193, 652.1709],
        [520.9910, 651.8912],
        [521.5818, 652.5458],
        [521.1691, 652.0177],
        [522.0889, 652.8828],
        [521.2069, 652.0886],
        [521.2466, 652.0983],
        [521.5360, 652.2930],
        [515.6593, 646.4862],
        [515.0188, 645.8041],
        [515.8705, 646.6949],
        [516.3422, 647.1633],
        [516.5104, 647.3068],
        [516.2269, 647.0814],
        [516.2878, 647.1510],
        [516.4515, 647.3134],
        [516.5623, 647.4258],
        [516.7218, 647.4740],
        [516.7695, 647.6068]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2808., 1281.],
        [2808., 1282.],
        [2

 68%|██████▊   | 1401/2060 [24:46<12:08,  1.11s/it]

tensor([[437.2544, 596.6899],
        [436.9552, 596.3190],
        [436.9645, 596.3516],
        [437.0758, 596.4076],
        [437.8843, 597.2090],
        [437.3712, 596.8005],
        [437.6105, 596.9657],
        [437.4232, 596.9015],
        [438.2830, 597.7455],
        [438.1083, 597.4814],
        [438.3744, 597.7981],
        [438.1770, 597.5880],
        [438.6608, 598.1992],
        [439.3031, 598.7952],
        [438.2635, 597.6581],
        [438.5244, 597.9291],
        [439.5978, 599.0876],
        [438.3170, 597.7040],
        [438.5509, 597.9482],
        [433.1794, 592.5599],
        [433.6210, 592.8586],
        [428.1902, 586.9867],
        [437.9718, 597.7594],
        [435.3939, 594.5417],
        [433.6176, 592.9164],
        [434.1812, 593.4276],
        [433.9563, 593.1150],
        [433.9108, 593.1016],
        [433.2257, 592.4836],
        [434.7308, 593.9442]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 541.0000, 3074.0000],
        [ 541.0000, 3075.0

 78%|███████▊  | 1601/2060 [28:17<07:40,  1.00s/it]

tensor([[502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [502.6855, 629.5026],
        [505.4393, 632.2180],
        [505.9858, 632.6302],
        [505.4393, 632.2180],
        [505.4393, 632.2180],
        [505.4393, 632.2180],
        [505.4393, 632.2180],
        [504.7008, 631.4673],
        [505.9858, 632.6302],
        [505.4393, 632.2180],
        [505.4393, 632.2180],
        [505.4393, 632.2180]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[2771., 1393.],
        [2771., 1393.],
        [2

 87%|████████▋ | 1801/2060 [31:40<04:26,  1.03s/it]

tensor([[331.8955, 491.2869],
        [333.1819, 492.7561],
        [331.7388, 491.1604],
        [332.2490, 491.6084],
        [331.5278, 490.9834],
        [331.8289, 491.4150],
        [331.7871, 491.3694],
        [331.3308, 490.6200],
        [331.6692, 491.1448],
        [332.1619, 491.5892],
        [331.2571, 490.4918],
        [331.5166, 490.9136],
        [331.4036, 490.7313],
        [330.1069, 489.3029],
        [331.2317, 490.5721],
        [331.2029, 490.5437],
        [330.7625, 490.0775],
        [331.3887, 490.7374],
        [330.6292, 489.9110],
        [341.1306, 500.9581],
        [344.9363, 504.4686],
        [339.6003, 499.6525],
        [339.0591, 499.1278],
        [339.2324, 499.3733],
        [337.8984, 498.3087],
        [339.9507, 500.0834],
        [339.6926, 499.7108],
        [349.1062, 507.7505],
        [339.0842, 499.1754],
        [338.6040, 498.8973]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 740.9999, 2181.0000],
        [ 740.9999, 2180.0

 97%|█████████▋| 2001/2060 [35:04<00:59,  1.01s/it]

tensor([[301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.6147, 472.4102],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869],
        [301.9487, 472.5869]], device='cuda:0', grad_fn=<AddBackward0>) tensor([[ 790., 1984.],
        [ 790., 1984.],
        [ 

1 tensor(688.6138, device='cuda:0', grad_fn=<AddBackward0>)
